apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
        labels: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3