apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-pod
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: myapp